name: Release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Publish plugin
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_PUBLISH_TOKEN }}
        run: ./gradlew publishMods --no-daemon -PnoDryPublish
